package de.miltschek.integrations;

/**
 * Contains data of a Slack Message.
 */
public class SlackMessage {
	private String channelId;
	private String channelName;
	private String command;
	private String text;
	private String userId;
	private String userName;

	/**
	 * Returns an ID of a channel, if available.
	 * @return an ID of a channel, if available.
	 */
	public String getChannelId() {
		return channelId;
	}
	
	/**
	 * Returns a channel name, if available.
	 * @return a channel name, if available.
	 */
	public String getChannelName() {
		return channelName;
	}
	
	/**
	 * Returns a command name, if generated by a command call.
	 * @return a command name, if generated by a command call.
	 */
	public String getCommand() {
		return command;
	}
	
	/**
	 * Returns the text of a message, if available.
	 * @return the text of a message, if available.
	 */
	public String getText() {
		return text;
	}
	
	/**
	 * Returns an ID of the user that created the message, if available.
	 * @return an ID of the user that created the message, if available.
	 */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Returns a name of the user that created the message, if available.
	 * @return a name of the user that created the message, if available.
	 */
	public String getUserName() {
		return userName;
	}
	
	/**
	 * Sets the ID of the channel.
	 * @param channelId the ID of the channel.
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}
	
	/**
	 * Sets the name of the channel.
	 * @param channelName the name of the channel.
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}
	
	/**
	 * Sets the command name.
	 * @param command the command name.
	 */
	public void setCommand(String command) {
		this.command = command;
	}
	
	/**
	 * Sets the text of the message.
	 * @param text the text of the message.
	 */
	public void setText(String text) {
		this.text = text;
	}
	
	/**
	 * Sets the ID of the user that created the message.
	 * @param userId the ID of the user that created the message.
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	/**
	 * Sets the name of the user that created the message.
	 * @param userName the name of the user that created the message.
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	/**
	 * Prints the internal data of the object.
	 */
	@Override
	public String toString() {
		return this.command + " " + this.text
				+ " from " + this.userName + " (" + this.userId + ")"
				+ " channel " + this.channelName + " (" + this.channelId + ")";
	}
}
